import type { TimetableItem } from '@/shared/types/usas';
import type { TimeFormat } from '@/shared/types/usas';
import { getShortTimeRange } from '@/shared/lib/timetableTime';
import { sanitizeSingleLine, sanitizeTextForShare } from '@/shared/lib/security';
import { extractDayName } from '@/shared/lib/dayFormat';

function parseTimeToMinutes(timeStr: string | undefined): number {
  if (!timeStr) return 0;
  const match = timeStr.match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);
  if (!match) return 0;
  let h = parseInt(match[1], 10);
  const m = parseInt(match[2], 10);
  const ampm = match[3]?.toUpperCase();
  if (ampm === 'PM' && h < 12) h += 12;
  if (ampm === 'AM' && h === 12) h = 0;
  return h * 60 + m;
}

function normalizeGroup(groupStr: string | undefined): string {
  if (!groupStr) return '';
  return sanitizeSingleLine(groupStr, 32).replace(/^GRP/i, 'G');
}

function buildDayGroups(timetable: TimetableItem[] = []): Map<string, TimetableItem[]> {
  const dayGroups = new Map<string, TimetableItem[]>();

  timetable.forEach((item: TimetableItem) => {
    const day = extractDayName(item.day) || 'LAIN';
    const classes = dayGroups.get(day) ?? [];
    classes.push(item);
    dayGroups.set(day, classes);
  });

  dayGroups.forEach((classes) => {
    classes.sort((a, b) => parseTimeToMinutes(a.start_time) - parseTimeToMinutes(b.start_time));
  });

  return dayGroups;
}

function formatTimeRange(startTime: string | undefined, endTime: string | undefined, timeFormat: TimeFormat): string {
  if (!startTime) return 'TBA';
  return getShortTimeRange(startTime, endTime, timeFormat);
}

function buildFullShareText(timetable: TimetableItem[] = [], studentName = '', matricNo = '', timeFormat: TimeFormat = '24h') {
  if (!timetable || timetable.length === 0) return '';

  const dayOrder = ['ISNIN', 'SELASA', 'RABU', 'KHAMIS', 'JUMAAT', 'SABTU', 'AHAD'];
  const dayGroups = buildDayGroups(timetable);
  let text = 'JADUAL KULIAH SAYA\n';
  text += `${sanitizeTextForShare(studentName || 'Pelajar USAS', 80)}\n`;
  text += `No. Matrik: ${sanitizeSingleLine(matricNo, 32)}\n`;
  text += '----------------------------------------\n\n';

  dayOrder.forEach(day => {
    const classes = dayGroups.get(day);
    if (!classes) return;
    text += `${day}\n`;
    classes.forEach(c => {
      const time = sanitizeSingleLine(formatTimeRange(c.start_time || c.jadual, c.end_time, timeFormat).replace('-', ' - '), 64);
      const code = sanitizeSingleLine(c.course_id || c.kod_kursus || '', 64);
      const name = sanitizeTextForShare(c.course_name || c.kursus || '', 160);
      const group = normalizeGroup(c.group || c.kumpulan);
      const loc = sanitizeTextForShare(c.location || '', 160);
      text += `  ${code}${group ? ` (${group})` : ''}: ${name}\n`;
      text += `  Time: ${time}\n`;
      if (loc) text += `  Location: ${loc}\n`;
      text += '\n';
    });
  });

  text += '----------------------------------------\n';
  text += 'Generated by Portal Jadual USAS';
  return text;
}

function buildCompactShareText(timetable: TimetableItem[] = [], matricNo = '', timeFormat: TimeFormat = '24h') {
  if (!timetable || timetable.length === 0) return '';

  const dayOrder = ['ISNIN', 'SELASA', 'RABU', 'KHAMIS', 'JUMAAT', 'SABTU', 'AHAD'];
  const dayGroups = buildDayGroups(timetable);

  const parts: string[] = [];
  dayOrder.forEach(day => {
    const classes = dayGroups.get(day);
    if (!classes) return;
    const items = classes.map(c => {
      const time = formatTimeRange(
        sanitizeSingleLine(c.start_time, 32),
        sanitizeSingleLine(c.end_time, 32),
        timeFormat,
      );
      const code = sanitizeSingleLine(c.course_id || '', 64);
      const group = normalizeGroup(c.group || c.kumpulan);
      return group ? `${code}-${group} ${time}` : `${code} ${time}`;
    }).join(', ');
    parts.push(`${day}: ${items}`);
  });

  return `Jadual Kuliah ${sanitizeSingleLine(matricNo, 32)}\n\n${parts.join('\n\n')}`;
}

export { buildCompactShareText, buildFullShareText };
